### ISSUE TITLE
Build failure on Fedora 20

### ISSUE THREAD

**Issue by deepfire** [bergey/diagrams-opengl#17]
[deepfire@andromedae diagrams-opengl]$ ghc-pkg list --user
[deepfire@andromedae diagrams-opengl]$ git head-ref
4d804b62621a4c5e2d05d9c9a9cf14666bbe17ef
[deepfire@andromedae diagrams-opengl]$ cabal install --upgrade-dependencies
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: diagrams-opengl-1.0
rejecting: vinyl-0.3 (conflict: diagrams-opengl => vinyl>=0.2 && <0.3)
trying: vinyl-0.2.1
trying: transformers-0.4.1.0
rejecting: linear-1.10.1.1, 1.10.1, 1.10, 1.9.1, 1.9.0.1, 1.9, 1.8.1, 1.8, 1.7
(conflict: diagrams-opengl => linear>=1.3 && <1.7)
rejecting: linear-1.6, 1.4, 1.3.1.1, 1.3.1, 1.3 (conflict:
transformers==0.4.1.0, linear => transformers>=0.2 && <0.4)
rejecting: linear-1.2, 1.1.4, 1.1.2, 1.1.1, 1.0.1, 0.9.2, 0.9.1, 0.9, 0.8,
0.7, 0.6.1, 0.6, 0.5, 0.4.2.2, 0.4.2.1, 0.4.1, 0.2.0.2, 0.2 (conflict:
diagrams-opengl => linear>=1.3 && <1.7)

**Comment by deepfire** [comment]
Likely no more relevant.  Should we close this?

**Comment by bergey** [comment]
Your call.  As I wrote in my latest commit, I'm not maintaining this library any more.  I expect it will keep bitrotting unless someone else takes over.
